### ISSUE TITLE
Please mention how to get the github Oauth token for this to work properly.

### ISSUE THREAD

**Issue by xerosanyam** [Akryum/vue-curated-server#1]
Hello.
I've installed both client and server. But unable to fetch data from github.
Getting environment variable error.
When I hardcoded the values, I was still unable to get repository list from github and client was empty.

Thanks

**Comment by Akryum** [comment]
I think I have mistakenly written 'OAuth token' but it should be a [Personal Access Token](https://github.com/settings/tokens) instead.

**Comment by xerosanyam** [comment]
okay. please mention the permissions/access Personal Access Token must have.

**Comment by Akryum** [comment]
You should be good with the `repo` permission.

**Comment by xerosanyam** [comment]
I think you mean public_repo ?
I updated my token with this, but it is still unable to fetch any packages.

**Comment by Akryum** [comment]
In fact you shouldn't need any permission, just leave the checkboxes unselected. Did you also setup the other environment variables like `SOURCE_REPO`? Do you have any console output to share?

**Comment by xerosanyam** [comment]
please take a look at these screenshots.
after setting environment, the process still throws err
![screenshot from 2017-10-05 16-28-44](https://user-images.githubusercontent.com/3167278/31224154-6b18c75a-a9ea-11e7-8186-c74a6be6a1b2.png)
after setting src/providers/github.js in GITHUB_TOKEN = xxxx
![screenshot from 2017-10-05 16-29-09](https://user-images.githubusercontent.com/3167278/31224153-6af3ece6-a9ea-11e7-8b6c-d901ef1bb2e8.png)

but thankfully after setting both manually works :+1: 

so actually, setting up environment variable isn't working.

**Comment by Akryum** [comment]
When setting env variables on Linux, you either set the on the same command like this:

```bash
GITHUB_TOKEN=xxx npm run dev
```

Or with the [`export`](https://www.cyberciti.biz/faq/linux-unix-shell-export-command/) command if you are making multiple commands:

```bash
export GITHUB_TOKEN=xxx
npm run dev
```

**Comment by xerosanyam** [comment]
oh. thanks a lot for your time.
