### ISSUE TITLE
Server - Error with Deployment

### ISSUE THREAD

**Issue by jeremytubbs** [Akryum/vue-curated-server#4]
![image](https://user-images.githubusercontent.com/548888/37458154-7d8a9126-281a-11e8-8a61-2bb0f404fca2.png)

**Comment by LinusBorg** [comment]
Would you be able to give a little bit more context than "error with deployment"?

The reasonf for it not working is probably that your frontend is still trying to contact our backend (curated.vuejs.org) instead of your own.

**Comment by Akryum** [comment]
@LinusBorg It seems we have an issue with our own deployement 💥

**Comment by LinusBorg** [comment]
Ah, I see. Hence my request for context :D

**Comment by jeremytubbs** [comment]
I should of provided more context... just trying to give you a quick heads up.

**Comment by Akryum** [comment]
There was an issue with our deployment which is now working. Thanks for the report! 👍
